# 针对 .js 文件的排除
[[redirects]]
  from = "/blog-dev/assets/*"
  to = "/assets/:splat"
  status = 200

# 针对其他静态资源（如图片、字体等）的排除
[[redirects]]
  from = "/blog-dev/*.{png,jpg,jpeg,gif,svg,ico}"
  to = "/:splat"
  status = 200

# 其他所有非静态资源的重定向到 index.html
[[redirects]]
  from = "/blog-dev/*"
  to = "/:splat"
  status = 200
