[build]
  publish = "build"  # 如果没有构建步骤，请设置为项目根目录或实际的静态文件夹。

[[redirects]]
  from = "/blog-dev/*"
  to = "/blog-dev/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/blog-dev/index.html"
  status = 200